/*********************************************
 * Author:               AYMAN HARRAZ
 * Creation Data:        22 MAY, 2023
 * Version:              v1.0
 * Compiler:             GNU ARM GCC
 * Controller:		     STM32F401CCU6 (32-bit Architecture)
 * Processor:		     Cortex M4 (32-bit Architecture)
 * Layer:		         MCAL
 ********************************************/

#ifndef EXTI_CONFIG_H
#define EXTI_CONFIG_H

/*  OPTIONS
*   GROUP_4_SUB_0_BITS   
*   GROUP_3_SUB_1_BITS   
*   GROUP_2_SUB_2_BITS   
*   GROUP_1_SUB_3_BITS   
*   GROUP_0_SUB_4_BITS  
*/  
#define EXTI_LINE0_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE1_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE2_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE3_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE4_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE5_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE6_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE7_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE8_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE9_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE10_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE11_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE12_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE13_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE14_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE15_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE16_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE17_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE18_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE19_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE20_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE21_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE22_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE23_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE24_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE25_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE26_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE27_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE28_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE29_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE30_ENABEL 		MEXTI_DISABLE
#define EXTI_LINE31_ENABEL 		MEXTI_DISABLE


#define EXTI_LINE0_SENSE_MODE		MEXTI_DISABLE

#endif